Mitigate ReDOS vulnerablity (Fixes #1354)
SpiderLabs/owasp-modsecurity-crs pull request #1355
Opened 2019-04-15 16:08 UTC by s0md3v

`(?:/[dflr].*)*` can be changed to `(?:/[dflr].*)` because `.*` at the end of the sub-pattern will match the repetition of this sub-pattern anyway.

2019-04-16 08:30 UTC, theMiddleBlue commented
refer to #1354

2019-04-16 20:23 UTC, fgsch commented
Have you actually reproduced this issue with modsecurity?

2019-04-24 19:45 UTC, spartantri requested changes
The "fix" don't match common `for` loops, I made some slight changes and got it working with `"@rx \b(?:if(?:/i)?(?: not)?(?: exist\b| defined\b| errorlevel\b| cmdextversion\b|(?: |\().*(?:\bgeq\b|\bequ\b|\bneq\b|\bleq\b|\bgtr\b|\blss\b|==))|for\s?(?:/[dflr])?.* %+[\S]+ in\s?\(.*\)\s?do)"` 
Sample FOR internal command syntax:
```
 syntax-FOR-Files
       FOR %%parameter IN (set) DO command 
   
 syntax-FOR-Files-Rooted at Path   
       FOR /R [[drive:]path] %%parameter IN (set) DO command 
   
 syntax-FOR-Folders
       FOR /D %%parameter IN (folder_set) DO command 
   
 syntax-FOR-List of numbers   
       FOR /L %%parameter IN (start,step,end) DO command 
   
 syntax-FOR-File contents   
       FOR /F ["options"] %%parameter IN (filenameset) DO command 
   
       FOR /F ["options"] %%parameter IN ("Text string to process") DO command
   
 syntax-FOR-Command Results 
       FOR /F ["options"] %%parameter IN ('command to process') DO command
```

2019-04-24 20:06 UTC, s0md3v commented
I hope that fixes the issue.

2019-04-24 20:15 UTC, s0md3v commented
It should work now.

2019-04-24 21:11 UTC, fgsch commented
Can you explain why is the .*? needed? I believe changing the * to ? should suffice.

2019-04-24 21:15 UTC, spartantri commented
Hi @fgsch @theMiddleBlue @franbuehler I think you like better regex, can you please take a look/test, apparently this needs fixing for other use cases, as it is it won't match `for` loops and some `if` it is missing spaces so this regular expression has some false negatives as t:cmdline will replace all multiple spaces (including tab, newline, etc.) into one space (which can be missing depending on the payload).

I did my testing with this expression below to take care both the redos and the three false negatives I found:
`\b(?:if(?: /i)?(?: not)?(?: exist\b| defined\b| errorlevel\b| cmdextversion\b|(?: |\().*(?:\bgeq\b|\bequ\b|\bneq\b|\bleq\b|\bgtr\b|\blss\b|==))|for(?: /[dflr].*)?.*? %+[^ ]+ in\s\(.*\)\s?do)`

But if we use .* after the for switched then it make useless the switches section and it will be better to remove it as it is optional, this will make this regular expression more prone to false positives so we may need to address the for syntax a bit better but the text that would match will look a bit weird.

Test at least with:
```
FOR %%parameter IN (set) DO command 
FOR /R [[drive:]path] %%parameter IN (set) DO command 
FOR /D %%parameter IN (folder_set) DO command 
FOR /L %%parameter IN (start,step,end) DO command 
FOR /F ["options"] %%parameter IN (filenameset) DO command 
FOR /F ["options"] %%parameter IN ("Text string to process") DO command
FOR /F ["options"] %%parameter IN ('command to process') DO command
FOR it doesn't matter what or how many spaces %until_you_get_here_no_space_permitted in (whatever) do
for getting 50 %: in (english) don't do this
```

2019-04-24 23:13 UTC, fgsch commented
I'd say let's concentrate on dealing with the problem in this PR and fix FNs in a different PR.
I've tested the following list only replacing * with ? and everything is working:

```
for %variable in (set) do command
for %%variable in (set) do command
for /d %variable in (set) DO command
for /r c:\ %variable in (set) do command
for /l %variable in (1,1,2) do command
for /f %variable in (fileset) do command
for /f %variable in ("string") do command
for /f %variable in ('command') do command
for /f "usebackq" %variable in (`command`) do command
```

I will add this to the test suite so we have something we can work on as currently there are no tests for this rule.

2019-05-03 22:59 UTC, fgsch commented
I think if we change the `for(?:/[dflr].*)* %+[^ ]+ in\(.*\)\s?do` part to `for(?:/[dflr].*)? %+[^ ]+ in\(.*\)\s?do` we are good to go.

Any objections? @s0md3v can you update it?

2019-07-04 17:07 UTC, lifeforms commented
Unfortunately, the source branch of the PR seems to be deleted, so I can't seem to push updates to it. Therefore I just made a new PR with the fix in #1472. I've also added a lot of extra tests, which pass after the fix, so I'm confident that the rule is fine.

Thanks for reporting and thanks to our fine contributors for fixing the rule!

2019-07-04 17:07 UTC, closed without merging